#!/bin/bash




#---------------------------------------------UNINSTALL BASIC PACKAGES & REMOVE DIRECTORY STRUCTURE---------------------------------------------


sudo rm -rfd ~/Apps/ros2_ws #FK this directory only would exist because of a previous version of this install script
sudo rm -rfd ~/Apps/LIO-SAM #FK this directory only would exist because of a previous and different version of this install script
sudo rm -rfd ~/Apps/colcon_SPARK-SLAM #FK this directory only would exist because of a different version of this install script
sudo rm -rfd ~/Apps/ndt_omp_ros2
sudo rm -rfd ~/Apps/lidarslam_ros2

#FK note: apt purge destroys any user configuration files left behind too
sudo apt purge python3-colcon-common-extensions -y 
sudo apt purge python3-rosdep -y
sudo apt autoremove -y



#---------------------------------------------REMOVE FILES GENERATED BY COLCON/CMAKE---------------------------------------------


sudo rm /etc/ros/rosdep/sources.list.d/20-default.list
sudo rm -rfd ~/.ros
